#!/bin/bash

cat >/etc/nginx/sites-available/idp <<EOL

server {
  listen 80;
  server_name $1;
  return 301 https://$1\$request_uri;
}

server {
  listen 80;
  server_name persona.$1;

  location / {
      proxy_pass         http://127.0.0.1:10002/;
      proxy_redirect     off;

      proxy_set_header   Host             \$host;
      proxy_set_header   X-Real-IP        \$remote_addr;
      proxy_set_header   X-Forwarded-For  \$proxy_add_x_forwarded_for;
      proxy_max_temp_file_size 0;

      client_max_body_size       10m;
      client_body_buffer_size    128k;

      proxy_connect_timeout      150;
      proxy_send_timeout         150;
      proxy_read_timeout         150;

      proxy_buffer_size          4k;
      proxy_buffers              4 32k;
      proxy_busy_buffers_size    64k;
      proxy_temp_file_write_size 64k;
  }

}

server {
    listen       443 ssl;
    server_name  $1;

    access_log  off;
    error_log off;

    ssl on;
    ssl_certificate /vagrant/certs/certificate.pem;
    ssl_certificate_key /vagrant/certs/certificate.key;

    ssl_prefer_server_ciphers on;
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
    # forward secrecy
    ssl_ciphers ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-RC4-SHA:ECDHE-RSA-AES128-SHA:AES128-GCM-SHA256:RC4:HIGH:!MD5:!aNULL:!EDH:!CAMELLIA:!PSK:!SRP;
    ssl_session_cache    shared:SSL:10m;
    ssl_session_timeout  10m;

    add_header Strict-Transport-Security max-age=31536000;

    location =/.well-known/browserid {
      alias /vagrant/support_document;
      types {}
      default_type application/json;
    }

    location /persona/ {
        proxy_pass         http://127.0.0.1:8999/;
        proxy_redirect     off;

        proxy_set_header   Host             \$host;
        proxy_set_header   X-Real-IP        \$remote_addr;
        proxy_set_header   X-Forwarded-For  \$proxy_add_x_forwarded_for;
        proxy_max_temp_file_size 0;

        client_max_body_size       10m;
        client_body_buffer_size    128k;

        proxy_connect_timeout      150;
        proxy_send_timeout         150;
        proxy_read_timeout         150;

        proxy_buffer_size          4k;
        proxy_buffers              4 32k;
        proxy_busy_buffers_size    64k;
        proxy_temp_file_write_size 64k;
    }
}

EOL

service nginx restart

